### ISSUE TITLE
Cannot have index signature type decl in TypeScript class

### ISSUE THREAD

**Issue by crazytoucan** [alangpierce/sucrase#250]
Sucrase chokes on the following input, where `tsc` does not:

```ts
// src/foo.ts
export class Foo {
    [name: string]: any;
}
```

```sh
$ sucrase src -d out --transforms typescript
src/foo.ts -> out/foo.js
Error: Error transforming src/foo.ts: Expected class context ID on computed name open bracket.
    at getNameCode (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/util/getClassInfo.js:232:13)
    at getClassInfo (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/util/getClassInfo.js:69:24)
    at RootTransformer.processClass (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/transformers/RootTransformer.js:154:50)
    at RootTransformer.processToken (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/transformers/RootTransformer.js:129:12)
    at RootTransformer.processBalancedCode (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/transformers/RootTransformer.js:123:12)
    at RootTransformer.transform (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/transformers/RootTransformer.js:78:10)
    at transform (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/index.js:47:25)
    at buildFile (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/cli.js:84:48)
    at <anonymous>
```

**Comment by crazytoucan** [comment]
Found the online tool! Cool stuff. Link with repro: https://sucrase.io/#selectedTransforms=typescript&code=export%20class%20Foo%20%7B%0A%20%20%5Bname%3A%20string%5D%3A%20any%3B%0A%7D

**Comment by alangpierce** [comment]
Thanks for the report! Hopefully should be an easy enough fix.
