### ISSUE TITLE
TODO: Cannot have generic args on object field values in TypeScript

### ISSUE THREAD

**Issue by crazytoucan** [alangpierce/sucrase#251]
```ts
// src/foo.ts
export const Foo = {
    bar<T>() {
        return;
    }
};
```

```sh
$ sucrase src -d out --transforms typescript
src/foo.ts -> out/foo.js
Error: Error transforming src/foo.ts: TODO
    at tsStartParseObjPropValue (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/plugins/typescript.js:1258:11)
    at parseObjPropValue (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/traverser/expression.js:833:46)
    at parseObj (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/traverser/expression.js:756:5)
    at parseExprAtom (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/traverser/expression.js:487:7)
    at parseExprSubscripts (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/traverser/expression.js:258:20)
    at parseMaybeUnary (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/traverser/expression.js:244:20)
    at parseExprOps (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/traverser/expression.js:184:20)
    at parseMaybeConditional (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/traverser/expression.js:157:20)
    at baseParseMaybeAssign (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/traverser/expression.js:141:20)
    at tsParseMaybeAssign (/Users/alexr/.config/yarn/global/node_modules/sucrase/dist/parser/plugins/typescript.js:1306:49)
```

Link: https://sucrase.io/#code=export%20const%20Foo%20%3D%20%7B%0A%20%20%20%20bar%3CT%3E()%20%7B%0A%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20%7D%0A%7D%3B%0A

Curiously, Sucrase behavior is compatible with your sample's Babel stack. ☺️

**Comment by crazytoucan** [comment]
Current reasonable workaround is to transform that into an arrow function:

```ts
export const Foo = {
    bar: <T>() => {
        return;
    }
};
```

https://sucrase.io/#code=export%20const%20Foo%20%3D%20%7B%0A%20%20%20%20bar%3A%20%3CT%3E()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20%7D%0A%7D%3B%0A

**Comment by alangpierce** [comment]
Haha, yeah, Sucrase's parser is forked from Babel's, and that case also isn't implemented in Babel TS parsing. I'll look into how hard it would be to just implement, or it's possible it's been implemented recently in Babel and I just need to port the implementation.
