### ISSUE TITLE
Require is not defined after sucrase transform in terminal

### ISSUE THREAD

**Issue by nelson777** [alangpierce/sucrase#524]
I'm getting the following error after I tried to run code **in the terminal** that was transpiled by sucrase:

```
(node:10762) ExperimentalWarning: The ESM module loader is experimental.
file:///vagrant/backend/dist/server.js:1
"use strict"; function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }var _http = require('http'); var _http2 = _interopRequireDefault(_http);
                                                                                                                         ^

ReferenceError: require is not defined
    at file:///vagrant/backend/dist/server.js:1:122
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:176:24)

```

It's only js code (no Typescript) converted only because of imports. I used the following command to convert the code:

`sucrase src/ -d ./dist --transforms imports`

I used the following command to run the code:

`node dist/server.js`

the conversion process occured flawlessly, but when I tried to run it the problem happens. That's very strange because require is a native node instruction.

**Comment by nelson777** [comment]
I discovered that it has to do with the `"type": "module"` option in my package.json. Removed and it worked. I'm still investigating but I'm closing this issue for now. If I get stuck again I'll reopen it later.
