### ISSUE TITLE
Sucrase SyntaxError - (7:3)

### ISSUE THREAD

**Issue by nmcpmadmin** [alangpierce/sucrase#815]
Just ran this for the first time and I'm getting these errors (possible typo in the source). 
Is this a known problem and is it serious?

(Terminal)
SyntaxError: Unexpected token, expected "," (7:3)
    at unexpected (__/node_modules/sucrase/dist/parser/traverser/util.js:99:15)
    at expect (__/node_modules/sucrase/dist/parser/traverser/util.js:86:5)
    at parseExprList (__/node_modules/sucrase/dist/parser/traverser/expression.js:973:20)
    at parseExprAtom (__/node_modules/sucrase/dist/parser/traverser/expression.js:549:7)
    at parseExprSubscripts (__/node_modules/sucrase/dist/parser/traverser/expression.js:276:20)
    at parseMaybeUnary (__/node_modules/sucrase/dist/parser/traverser/expression.js:257:20)
    at parseExprOps (__/node_modules/sucrase/dist/parser/traverser/expression.js:185:20)
    at parseMaybeConditional (__/node_modules/sucrase/dist/parser/traverser/expression.js:157:20)
    at baseParseMaybeAssign (__/node_modules/sucrase/dist/parser/traverser/expression.js:142:20)
    at tsParseMaybeAssignWithoutJSX (__/node_modules/sucrase/dist/parser/plugins/typescript.js:1580:45) {
  pos: 137,
  loc: Loc { line: 7, column: 3 }
}

**Comment by nmcpmadmin** [comment]
Issue #616 - (May 2001) seems very similar to this.

**Comment by nmcpmadmin** [comment]
This wasn't an issue with Sucrase. Please disregard. Involved Tailwind CSS and the simple error was in the tailwind config file.
